apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/rewrite-target":"/services","nginx.ingress.kubernetes.io/use-regex":"true"},"labels":{"app":"pataudi-finance"},"name":"pataudi-finance","namespace":"egov"},"spec":{"rules":[{"host":"pataudi-dev-hrupyog.sparrowsoftech.in","http":{"paths":[{"backend":{"service":{"name":"pataudi-finance","port":{"number":8080}}},"path":"/services","pathType":"Prefix"}]}}],"tls":[{"hosts":["pataudi-dev-hrupyog.sparrowsoftech.in"],"secretName":"pataudi-dev-hrupyog.sparrowsoftech.in-tls-certs"}]}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /services
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2025-02-15T09:27:40Z"
  generation: 3
  labels:
    app: pataudi-finance
  name: pataudi-finance
  namespace: egov
  resourceVersion: "4006173"
  uid: aa3abc57-255a-469d-9996-0b5b88321c2f
spec:
  rules:
  - host: pataudi-dev-hrupyog.sparrowsoftech.in
    http:
      paths:
      - backend:
          service:
            name: egov-finance
            port:
              number: 8080
        path: /services
        pathType: Prefix
  tls:
  - hosts:
    - pataudi-dev-hrupyog.sparrowsoftech.in
    secretName: pataudi-dev-hrupyog.sparrowsoftech.in-tls-certs
status:
  loadBalancer:
    ingress:
    - hostname: a116a4a4e6d344835a9bb3221cd106c6-1556349527.ap-south-1.elb.amazonaws.com
